language: ruby
env:
  global:
    # BoxView API Key
    secure: "QFH/gcuFT6bEXiXpAEIzSc+awrXB23dbhD1RUHneBjzHCAhRnTmyiNuXRt/YubOmt26ttEpQ0nh2D+DbW62ozFiaDaD05ho7Z7YgN1N6wvZD2ST+BiYPKVZWu8sTgQZ9ax8i9uTb3t+Ksu4X5g0cGg9vEdPFKC9PlQhEuwH7ojQ="
rvm:
  - 2.0.0
  - 2.1.0
notifications:
  email:
    recipients:
      - vinny@getlua.com
    on_success: change
    on_failure: always
branches:
  only:
    - master